language: php
dist: trusty
sudo: required
group: edge
 
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
# - hhvm
 
before_script:
  - composer self-update 1.8.4
  - composer install --prefer-source
  - composer require phpunit/phpunit 4.8.35
 
script:
  - vendor/bin/phpunit
